### ISSUE TITLE
tags are not handled properly upon vm creation

### ISSUE THREAD

**Issue by timspencer** [fog/fog-softlayer#21]
Hello again!  Thanks for adding the tags support.  I finally got some time to devote to chef-metal and softlayer again, and it looks like tags are not supported options during host creation, which is what chef-metal seems to want to do:

```
[2014-07-11T18:33:44-07:00] DEBUG: Re-raising exception: Excon::Errors::InternalServerError - machine[devops-tspencertest-db1] (@recipe_files::/Users/tspencer/src/myrepo/cookbooks/cp-ninjas/recipes/t.rb line 18) had an error: Excon::Errors::InternalServerError: Expected([200, 201]) <=> Actual(500 InternalServerError)
  response => #<Excon::Response:0x000001022cdbe0 @data={:body=>"{\"error\":\"The property 'tags' is not valid for ''.\",\"code\":\"SoftLayer_Exception_Public\"}", :headers=>{"X-Backside-Transport"=>"FAIL FAIL", "Date"=>"Sat, 12 Jul 2014 01:32:39 GMT", "Server"=>"Apache", "Vary"=>"Accept-Encoding", "Content-Type"=>"application/json", "X-Client-IP"=>"192.168.67.116", "Connection"=>"close", "Content-Length"=>"88"}, :status=>500, :remote_ip=>"66.228.119.116", :local_port=>55714, :local_address=>"10.0.1.33"}, @body="{\"error\":\"The property 'tags' is not valid for ''.\",\"code\":\"SoftLayer_Exception_Public\"}", @headers={"X-Backside-Transport"=>"FAIL FAIL", "Date"=>"Sat, 12 Jul 2014 01:32:39 GMT", "Server"=>"Apache", "Vary"=>"Accept-Encoding", "Content-Type"=>"application/json", "X-Client-IP"=>"192.168.67.116", "Connection"=>"close", "Content-Length"=>"88"}, @status=500, @remote_ip="66.228.119.116", @local_port=55714, @local_address="10.0.1.33">
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/excon-0.38.0/lib/excon/middlewares/expects.rb:6:in `response_call'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/excon-0.38.0/lib/excon/middlewares/response_parser.rb:26:in `response_call'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/excon-0.38.0/lib/excon/connection.rb:402:in `response'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/excon-0.38.0/lib/excon/connection.rb:272:in `request'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/fog-core-1.22.0/lib/fog/core/connection.rb:56:in `request'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/fog-softlayer-0.3.7/lib/fog/softlayer/core.rb:59:in `slapi_request'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/fog-softlayer-0.3.7/lib/fog/softlayer/compute.rb:117:in `request'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/fog-softlayer-0.3.7/lib/fog/softlayer/requests/compute/create_vms.rb:90:in `create_vms'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/fog-softlayer-0.3.7/lib/fog/softlayer/requests/compute/create_vm.rb:47:in `create_vm'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/fog-softlayer-0.3.7/lib/fog/softlayer/models/compute/server.rb:246:in `save'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/fog-core-1.22.0/lib/fog/core/collection.rb:51:in `create'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-metal-fog-0.6.2/lib/chef_metal_fog/fog_driver.rb:279:in `create_server'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-metal-fog-0.6.2/lib/chef_metal_fog/fog_driver.rb:173:in `allocate_machine'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-metal-0.12.1/lib/chef/provider/machine.rb:26:in `block in <class:Machine>'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/provider/lwrp_base.rb:45:in `block in action'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-metal-0.12.1/lib/chef/provider/machine.rb:31:in `block in <class:Machine>'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/provider/lwrp_base.rb:45:in `block in action'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-metal-0.12.1/lib/chef/provider/machine.rb:49:in `block in <class:Machine>'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/provider/lwrp_base.rb:45:in `block in action'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/provider.rb:120:in `run_action'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/resource.rb:637:in `run_action'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/runner.rb:49:in `run_action'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/runner.rb:81:in `each'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/runner.rb:81:in `block in converge'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/resource_collection.rb:96:in `execute_each_resource'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/runner.rb:80:in `converge'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/client.rb:345:in `converge'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/client.rb:431:in `do_run'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/client.rb:213:in `block in run'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/client.rb:207:in `fork'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/client.rb:207:in `run'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/application.rb:217:in `run_chef_client'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/application/client.rb:328:in `block in run_application'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/application/client.rb:317:in `loop'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/application/client.rb:317:in `run_application'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/lib/chef/application.rb:67:in `run'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-11.12.8/bin/chef-client:26:in `<top (required)>'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/bin/chef-client:23:in `load'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/bin/chef-client:23:in `<main>'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
  /Users/tspencer/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `<main>'
```

I still haven't had time to fully grok the way fog works, but perhaps we need to take the tags out of the options passed into create_vms.rb, and add them once the vm is created?

Thanks, and have fun!

-tspencer

**Comment by fernandes** [comment]
hey @timspencer have you still experiencing this issue? or may I close the issue?

**Comment by timspencer** [comment]
I haven't had a chance to check in quite a while.  I had to drop the project to get chef metal going because I couldn't get this going, so it'll take me a bit to try everything again.

I'll try to get to this sometime in the next week or two!

**Comment by fernandes** [comment]
ok @timspencer don't worry, I'm gonna close once its 6 months open, if you test and its still with same problem, I'm gonna open again, ok?

thank you
