### ISSUE TITLE
Network example not working for vlan creation

### ISSUE THREAD

**Issue by cbreden** [fog/fog-softlayer#59]
This example is bombing out with a parameter error:

https://github.com/fog/fog-softlayer/blame/master/examples/network.md#L213-L242

```
irb(main):024:0> opts = {:name => 'test-vlan', :datacenter => @sl.datacenters.by_name('sjc01'),
irb(main):025:1*         :router => @sl.datacenters.by_name('sjc01').routers[3], :network_space => 'PUBLIC'}
=> {:name=>"test-vlan", :datacenter=>  <Fog::Network::Softlayer::Datacenter
    id=168642,
    long_name="San Jose 1",
    name="sjc01"
  >, :router=>{"hostname"=>"fcr01a.sjc01", "id"=>82412}, :network_space=>"PUBLIC"}
irb(main):026:0> @sl.networks.create(opts)
ArgumentError: wrong number of arguments (0 for 1)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-softlayer-0.4.5/lib/fog/softlayer/requests/network/get_subnet_price_code.rb:21:in `get_subnet_price_code'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-softlayer-0.4.5/lib/fog/softlayer/models/network/network.rb:112:in `build_order'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-softlayer-0.4.5/lib/fog/softlayer/models/network/network.rb:77:in `create'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-softlayer-0.4.5/lib/fog/softlayer/models/network/network.rb:65:in `save'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/fog-core-1.30.0/lib/fog/core/collection.rb:51:in `create'
        from (irb):26
        from C:/Ruby193/bin/irb:12:in `<main>'
```

**Comment by mfbmina** [comment]
Hi @cbreden ! I'm having the same error here. Taking a look inside the code, the problem is in this line: https://github.com/fog/fog-softlayer/blob/master/lib/fog/softlayer/models/network/network.rb#L112

This occurs because that request needs some arguments (https://github.com/fog/fog-softlayer/blob/master/lib/fog/softlayer/requests/network/get_subnet_price_code.rb#L21) and they are not present. 

Looking deeper, every time that this request was called, I've never seen this in the method call, like here : https://github.com/fog/fog-softlayer/blob/master/lib/fog/softlayer/models/network/subnet.rb#L92.

Maybe @cphrmky can help us. :smile:

**Comment by thejohnlin** [comment]
I've enclosed a test snippet for adding a new VLAN using the softlayer_api gem. 

```require 'softlayer_api'

product_service = SoftLayer::Service.new("SoftLayer_Product_Order", :username => ENV["SL_API_USER"], :api_key => ENV["SL_API_KEY"], :endpoint_url => ENV["SL_API_ENDPOINT"])

order_template = {
          'complexType' => 'SoftLayer_Container_Product_Order_Network_Vlan',
          'name' => 'testvlan',
          'routerId' => '159110',
          'router' => 'bcr026.sjc01',
          'location' => '168642',
          'quantity' =>1,
          'packageId' =>0,
          'prices' =>[	
            {'id' => 27270}
          ]
        }
pp product_service.placeOrder(order_template)```

While I don't seem to be running into any errors on my end, I am coming across an exception that prohibits me from creating new VLANs on the account my user is tied to. 

Here's the dump:

```$ ruby test_vlan.rb
c:/Ruby193/lib/ruby/1.9.1/xmlrpc/client.rb:414:in `call': At the moment this account is not permitted to order additional VLANs. To request an additional VLAN, please contact our sales team for assistance (XMLRPC::FaultE
xception)
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/softlayer_api-3.0.2/lib/softlayer/Service.rb:267:in `call_softlayer_api_with_params'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/softlayer_api-3.0.2/lib/softlayer/Service.rb:196:in `method_missing'
        from test_vlan.rb:17:in `<main>'```

**Comment by cphrmky** [comment]
@cbreden et al, sorry for the slow response.

This has worked, it appears that you need an account where VLAN creation is enabled (which is what I tested on, and it still works on that account right now).

Need to improve the error handling and the docs around this, but if you contact your account rep and/or open a ticket requesting the ability to create VLANs on your account this will work.
